/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisisnumerico;

import static analisisnumerico.SecanteResultado.convertir;
import javax.swing.JOptionPane;

/**
 *
 * @author toto
 */
public class BiseccionResultado extends javax.swing.JPanel {

    public static String convertir(Funcion F, double x){
    String S="";
    String q=Double.toString(x);
    String f=F.getF();
    for(int i=0; i<f.length(); i++){
        if(f.charAt(i)=='x'){
            S+=q;
        }else
            S+=f.charAt(i);
    }
    return S;
    }
    
    
    /**
     * Creates new form BiseccionResultado
     */
    public BiseccionResultado(Funcion F,double lower, double upper, double eps) {
        initComponents();
        String f=F.getF();
        System.out.println(f);
        Evaluador e=new Evaluador();
        String l=convertir(F, lower);
        String u=convertir(F, upper);
        double fl=e.eval(l);
        double fu=e.eval(u);
        boolean sw=true;
        System.out.println(fl+"   "+fu);
        if(fl*fu>0){
            JOptionPane.showMessageDialog(null, "Limites no validos.");
            sw=false;
        }
        double mid= (upper+lower)/2;
        String m=convertir(F, mid);
        double fm=e.eval(m);
            
        while(Math.abs(fm)>eps && sw){
            System.out.println(mid);
            mid=(lower+upper)/2;
            l=convertir(F, lower);
            u=convertir(F, upper);
            fl=e.eval(l);
            fu=e.eval(u);
            m=convertir(F, mid);
            fm=e.eval(m);
             if(fl*fm>0)
                 lower=mid;
             else
                 upper=mid;
        }
        if(sw)
            JOptionPane.showMessageDialog(null, "Una raiz es :"+(lower+upper)/2);
            
        Menu v = new Menu(F);
                removeAll();
                v.setBounds(0, 0, 780, 480);
                add(v);
                v.setVisible(true);
                updateUI();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
