package analisisnumerico;;

import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Dimension;

/**
 *
 * @author toto
 */
public class Fondo extends javax.swing.JPanel {

    
    //Creates new form Fondo
    ImageIcon imafondo;
    public Fondo() {
        initComponents();
        imafondo=new ImageIcon(getClass().getResource("/Imagenes/pantalla.png"));
        setSize(780,480);
    }
    public void paint(Graphics g){
        Dimension t=getSize();
        imafondo=new ImageIcon(getClass().getResource("/Imagenes/pantalla.png"));
        g.drawImage(imafondo.getImage(), 0, 0, t.width, t.height, null);
        setOpaque(false);
        super.paint(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
