/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisisnumerico;

import javax.swing.JOptionPane;

/**
 *
 * @author toto
 */

public class SecanteResultado extends javax.swing.JPanel {
    /**
     * Creates new form SecanteResultado
     */
    public SecanteResultado(Funcion F,double lower, double upper, double eps) {
        initComponents();
        String f=F.getF();
        System.out.println(f);
        Evaluador e=new Evaluador();
        double fl=e.eval(f, lower);
        double fu=e.eval(f, upper);
        double mid= upper-((fu)*(upper-lower))/(fu-fl);
        double fm=e.eval(f, mid);
        while(Math.abs(fm)>eps){
            lower=upper;
            upper=mid;
            fl=e.eval(f, lower);
            fu=e.eval(f, upper);
            mid=upper-((fu)*(upper-lower))/(fu-fl);
            fm=e.eval(f, mid);
        }
        JOptionPane.showMessageDialog(null, "Una raiz es :"+mid);
        Menu v = new Menu(F);
        removeAll();
        v.setBounds(0, 0, 780, 480);
        add(v);
        v.setVisible(true);
        updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
